spring:
  datasource:
    url: jdbc:h2:mem:identity_test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: false

jwt:
  secret: test_secret_key
  expiration: 3600000