FROM gradle:7.6.1-jdk17

WORKDIR /app

# Copy gradle configuration files
COPY build.gradle settings.gradle ./
COPY gradle ./gradle

# Copy source code
COPY src ./src

# Run tests
CMD ["gradle", "test", "--no-daemon"]