server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_service}
    username: ${DB_USERNAME:task_app}
    password: ${DB_PASSWORD:task_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:changeThisToASecureRandomStringInProduction}
  issuer: ${JWT_ISSUER:identity-service}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.example.task: ${LOG_LEVEL:INFO}
    com.example.task.infrastructure.security: DEBUG
  file:
    name: ${LOG_FILE_PATH:/var/log/task-service.log}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html